apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - port: 8080
    targetPort: 9090
