apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-logging
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File /fluent-bit/etc/parser.conf
        Streams_File /fluent-bit/etc/stream.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port:   2020

    [INPUT]
        Name               node_exporter_metrics
        Tag                node_metrics
        Scrape_Interval    10
  
    [INPUT]
        Name               tail
        Tag                sensor-metrics
        Read_From_Head     true
        Parser             docker
        Path               /var/log/containers/sensor.log
        alias              sensor.stream
        Key                data
   
    [OUTPUT]
        Name           prometheus_exporter 
        Match          node_metrics
        Host           0.0.0.0
        Port           2021

    [OUTPUT]
        Name           stdout
        Match          new-data
        Format         msgpack

  parser.conf: |
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%d %H:%M:%S.%L

  stream.conf: |
    [STREAM_TASK]
        Name    data
        Exec    CREATE STREAM results WITH (tag='new-data') AS SELECT AVG(cpu) FROM STREAM:sensor.stream WINDOW TUMBLING (1 SECOND) WHERE temperature > 40;
